# -*- coding: utf-8 -*-
"""factorial

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10ILe2qGPjh7cRrYkDUM86R7LHoseWAkX
"""

n=5
fact=1
for i in range(1,n+1):
   fact=fact*i
   print(fact)